name: "publish"
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [
            # macos-latest, ubuntu-20.04, #! Unsupported Now...
            windows-latest,
          ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        name: Go to this repository

      - uses: denoland/setup-deno@v1
        name: Install deno
        with:
          deno-version: "1.32.4"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

        #! Unsupported Now...
      # - name: install dependencies (ubuntu only)
      #   if: matrix.platform == 'ubuntu-20.04'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      # - name: "Build Changelog"
      #   id: build_changelog
      #   uses: mikepenz/release-changelog-builder-action@v3.7.1

      - run: make build

      - uses: tauri-apps/tauri-action@v0
        name: Create release files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: bluetooth-battery-monitor-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Bluetooth battery monitor v__VERSION__"
          # releaseBody: ${{steps.build_changelog.outputs.changelog}}
          releaseBody: draft release
          releaseDraft: true
          prerelease: false
