name: Release GUI
on:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-20.04, windows-latest]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.7
        with:
          prefix-key: cargo-${{ matrix.platform }}

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Node.js cache
        uses: actions/cache@v4.2.0
        with:
          path: ${{ github.workspace }}/dar2oar_gui/frontend/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('dar2oar_gui/frontend/src/**/*.[jt]s', 'dar2oar_gui/frontend/src/**/*.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install frontend dependencies
        run: npm ci

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Github Release
        uses: tauri-apps/tauri-action@action-v0.5.18

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseName: 'Bluetooth Battery Monitor v__VERSION__'
          releaseBody: ${{ steps.changelog.outputs.changes }}
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          prerelease: false

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
