name: "publish"
on:
  push:
    tags: "*"

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [
            # macos-latest, ubuntu-20.04, #! Unsupported Now...
            windows-latest,
          ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        name: Go to this repository

      - uses: denoland/setup-deno@v1
        name: Install deno
        with:
          deno-version: "1.32.4"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

        #! Unsupported Now...
      # - name: install dependencies (ubuntu only)
      #   if: matrix.platform == 'ubuntu-20.04'
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: tauri-apps/tauri-action@v0
        name: Create release files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Bluetooth battery monitor v__VERSION__"
          releaseDraft: true
          prerelease: false
